version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release


  linux-vapor:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - run:
          name: Clone Vapor
          command: git clone -b 3 https://github.com/vapor/vapor.git
          working_directory: ~/
      - run:
          name: Switch Vapor to this Service revision
          command: swift package edit Service --revision $CIRCLE_SHA1
          working_directory: ~/vapor
      - run:
          name: Run Vapor unit tests
          command: swift test
          working_directory: ~/vapor



  linux-fluent-sqlite:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - run:
          name: Clone Fluent SQLite
          command: git clone -b master https://github.com/vapor/fluent-sqlite.git
          working_directory: ~/
      - run:
          name: Switch Fluent SQLite to this Service revision
          command: swift package edit Service --revision $CIRCLE_SHA1
          working_directory: ~/fluent-sqlite
      - run:
          name: Run Fluent SQLite unit tests
          command: swift test
          working_directory: ~/fluent-sqlite

  linux-fluent-mysql:
    docker:
      - image: codevapor/swift:4.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: vapor_database
          # MYSQL_ROOT_HOST: %
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
    steps:
      - run:
          name: Clone Fluent MySQL
          command: git clone -b 3 https://github.com/vapor/fluent-mysql.git
          working_directory: ~/
      - run:
          name: Switch Fluent MySQL to this Service revision
          command: swift package edit Service --revision $CIRCLE_SHA1
          working_directory: ~/fluent-mysql
      - run:
          name: Run Fluent MySQL unit tests
          command: swift test
          working_directory: ~/fluent-mysql

  linux-fluent-postgresql:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - run:
          name: Clone Fluent PostgreSQL
          command: git clone -b 1 https://github.com/vapor/fluent-postgresql.git
          working_directory: ~/
      - run:
          name: Switch Fluent PostgreSQL to this Service revision
          command: swift package edit Service --revision $CIRCLE_SHA1
          working_directory: ~/fluent-postgresql
      - run:
          name: Run Fluent PostgreSQL unit tests
          command: swift test
          working_directory: ~/fluent-postgresql

  linux-redis:
    docker:
      - image: codevapor/swift:4.1
      - image: redis:3.2
    steps:
      - run:
          name: Clone Redis
          command: git clone -b master https://github.com/vapor/redis.git
          working_directory: ~/
      - run:
          name: Switch Redis to this Service revision
          command: swift package edit Service --revision $CIRCLE_SHA1
          working_directory: ~/redis
      - run:
          name: Run Redis unit tests
          command: swift test
          working_directory: ~/redis

  linux-jwt:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - run:
          name: Clone JWT
          command: git clone -b master https://github.com/vapor/jwt.git
          working_directory: ~/
      - run:
          name: Switch JWT to this Service revision
          command: swift package edit Service --revision $CIRCLE_SHA1
          working_directory: ~/jwt
      - run:
          name: Run JWT unit tests
          command: swift test
          working_directory: ~/jwt

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-vapor
      - linux-fluent-sqlite
      - linux-fluent-mysql
      - linux-fluent-postgresql
      - linux-redis
      # - linux-jwt # doesn't use services yet
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      # - macos
      